vault:
  path: ${vault_path}

telegram:
  token: ${telegram_bot_token}
  username: ${telegram_bot_username}
  allowed-user-ids:
    - ${telegram_allow_userid}

spring:
  ai:
    ollama:
      base-url: ${ollama_url}
      chat:
        options:
          model: ${ollama_model}
          temperature: 0.1
